middleware-generic.xml
Details: Reason for change: Integrate unit test framework
Test Procedure: Invoked unit test on every PR
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 08270fd2e620d5c2da6dd0f99e2816aefad30ef3
=> RDK-56730 - Auto PR for rdkcentral/meta-rdk-video 11

middleware-generic.xml
Reason for change: Integrate unit test framework
Test Procedure: Invoked unit test on every PR
=> RDK-56730: Unit test framework for routerDiscovery

middleware-generic.xml
Reverted meta-rdk to use last known good tag.
=> STBT-49895: Update middleware-generic.xml

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: 56fd10f4436bc056cab156cc1fbadf7319975e0e
=> RDK-56491 - Auto PR for rdkcentral/meta-rdk 3

middleware-generic.xml
RDK-52635 [RDKE-MW][tr69hostif] Remove all product/platform/region specific build time configs/variables/distro features
Priority:P1
=> RDK-52635 [RDKE-MW][tr69hostif] Remove all product/platform/region specific build time configs/variables/distro features

middleware-generic.xml
Details: Update packagegroup-middleware-layer.bb
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 73e31a1c72632578c43a969706041c325c24f1f9
=> RDKEMW-2085 - Auto PR for rdkcentral/meta-middleware-generic-support 14

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: ad417df724435ec23957738f4e5d18fb856e8b88
=> RDKEMW-2973 - Auto PR for rdkcentral/meta-rdk 23

middleware-generic.xml
Details: Reason for change: change default voice
Test Procedure: Mentioned in ticket
Risks: Low
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 4dd2e71a0dee84d0666e3b878ad075e1ae544fb2
=> RDKEMW-2503 - Auto PR for rdkcentral/meta-rdk-video 18

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 26997607a2283d514f53434cefde39ef5cfa98a7
=> RDKWEMW-2235 - Auto PR for rdkcentral/meta-rdk-video 6

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 28e976c3fb8460e2221a8f5b05c383fd62aca839
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: d01e310d152f9608e3a288081e826d7d3578a4ab
=> RDKEMW-1020 - Auto PR for rdkcentral/meta-middleware-generic-support 90

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 0a02edc491caa0bac2fbbb57ef05421b8e7111bd
=> DELIA-67586 - Auto PR for rdkcentral/meta-middleware-generic-support 87

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 5a481b0689f78913d20d2f9e463b58d5981d8e21
=> RDKEMW-921 - Auto PR for rdkcentral/meta-rdk-video 86

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 159e5f2f867e3eac4119a4007ed0341a3360a071
=> RDKEMW-921 - Auto PR for rdkcentral/meta-middleware-generic-support 105

middleware-generic.xml
Details: Update sysint_git.bb
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: d27e4b803a07d793b815f29641ebab553a487909
=> RDKEMW-2321 - Auto PR for rdkcentral/meta-rdk-video 83

middleware-generic.xml
Details: Reason for change: Add COM-RPC support for DeviceDiagnostics
Test Procedure: Test DeviceDiagnostics - All APIs
Risks: Medium
Priority: P1
Signed-off-by:Dineshkumar P [dinesh_kumar2@comcast.com]
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: cf69dc9c5a2f9ea7fae2b133d83b16ccc18cd021
=> RDKEMW-1009 - Auto PR for rdkcentral/meta-rdk-video 55

middleware-generic.xml
Details: Reason for change: this changes involve updating the trace level handling
Test Procedure: please referred from the ticket
Risks: Medium
Signed-off-by: Thamim Razith <ThamimRazith_AbbasAli@comcast.com>
Change-Id: I9007efba82382977a8eef15e45bcead50bc3a97e
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 0e26ca4c5612bf4f2396a0e575378d27477c2f93
=> RDKEMW-3094 - Auto PR for rdkcentral/meta-rdk-video 64

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: e383b8132e9d9e66adb907c0138eb24b5db90008
=> RM-15 - Auto PR for rdkcentral/meta-rdk 31

middleware-generic.xml
Details: Reason for change: Bug fix
Test Procedure: Mentioned in ticket
Risks: Low
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 0643f9cabe6ca7d6c39a38399e573125c9941219
=> RDKEMW-3169 - Auto PR for rdkcentral/meta-rdk-video 92

middleware-generic.xml
Details: Reason for change: Updated the networkmanager plugin version to 0.13.0
Test Procedure: NA
Risks: low
Priority: P2
Signed-off-by: Gururaaja ESR <gururaja_erodesriranganramlingham@comcast.com>
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 48579b743cbe3c88218b4e180ed51f5e3dfeeae6
=> RDKEMW-2148 - Auto PR for rdkcentral/meta-rdk-video 106

middleware-generic.xml
Details: Reason for change: Enable PERSIST_LOG_MON_REF for telemetry available from 1.4.0
Test Procedure: Build and verify
Risks: Medium
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: fae7962c184b9230a4442998c4850358f1043009
=> RDK-57058 - Auto PR for rdkcentral/meta-rdk-video 98

middleware-generic.xml
Details: Reason for change:  sync with stable2 in gerrit 3/31/2025
Test Procedure:
Risks:              Low
Change-Id: I71d7c72363bf8c8e9a884fc0016771c5369f2e5e
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 0358e44ef24f70e0ca84e2198dbf3b8a2f8c1749
=> XCTRL-400 - Auto PR for rdkcentral/meta-middleware-generic-support 115

middleware-generic.xml
Details: Update sysint release SHA and Revision
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 4ed8d6b756238a1cb1112bf2ad3b722aae2a2c81
=> RDKEMW-3268 - Auto PR for rdkcentral/meta-middleware-generic-support 130

middleware-generic.xml
Details: Reason for change: Moved the wpeframework-networkmanager.service to thunder-startup-services
Test Procedure: check the command "systemctl status NetworkManager"
Risks: Medium
Priority: P1
Signed-off-by: Gururaaja ESR<gururaja_erodesriranganramlingham@comcast.com>
- Repository: rdkcentral/thunder-startup-services, Merge Commit SHA: 4c8d327730240b5b6dccf50403f90d8a1366fc48
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: ec1b252e4c58caa1f11c008ae2701a1a4cf7dd89
=> RDKEMW-3311 - Auto PR for rdkcentral/thunder-startup-services 36

middleware-generic.xml
Details: Reason for change: webconfig_metadata.json and webconfig_video_metadata.json needs to be generalized.
Test Procedure:  Tested and verified
Risks:            Medium
Priority:        P1
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: db5e17af51e28daed69ba3c6bcce29fdaa314725
=> RDKEMW-3071 - Auto PR for rdkcentral/meta-rdk 44

middleware-generic.xml
Details: Upgrade larboard srcrev and move libloader-app's build dir out of source tree.
Change-Id: I1c35a5e3b6cba9bdb2980e563b0a0b7e9580a9e6
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: a1075cc89c3321b31fb35d010a3dca6aae3bb79d
=> RDKEMW-3417 - Auto PR for rdkcentral/meta-rdk-video 135

middleware-generic.xml
Details: Reason for change: Updating thunder-startup-services tag
Test Procedure: Build and verify.
Risks: low
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: a6463e8af0d934e8f1d28f2da7e9c32e7562bb4b
=> RDKEMW-2952 - Auto PR for rdkcentral/meta-middleware-generic-support 164

middleware-generic.xml
Details: Patch release for crashes on top of previous log look up feature.
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 5146bf4a992c70f8f1d2fb3b432907e24d7ba953
=> NO-TICKET - Auto PR for rdkcentral/meta-middleware-generic-support 170

middleware-generic.xml
Details: deleting and recreating the file since the github action is not displayed
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: c252f6d505e861761837cbb78223e39033b53466
=> NO-TICKET - Auto PR for rdkcentral/meta-rdk 51

middleware-generic.xml
Reason for change: bringup-enc-playback
Risks: Low
Priority: P1
Signed-off-by:mkooda197@cable.comcast.com
=> RDKEMW-3062: bringup-enc-playback

middleware-generic.xml
Details: re adding workflow file
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: 0dcf97cbf9cd225db56ff43d14f0442ae9abbe1c
=> NO-TICKET - Auto PR for rdkcentral/meta-rdk 52

middleware-generic.xml
Details: Release PR for 1.2.0
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 4ac5ce912e5f5a236b44ec40b604cdb07df79bba
=> NO-TICKET - Auto PR for rdkcentral/meta-middleware-generic-support 182

middleware-generic.xml
Details: Release PR for 1.2.0
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: f2fb5d8c0eaa4959aae258d982f5702390cb84dc
=> NO-TICKET - Auto PR for rdkcentral/meta-rdk 56

middleware-generic.xml
Details: Release PR for 1.2.0
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 5bcfea7813fd5951de9d2fd42db84c28de393191
=> NO-TICKET - Auto PR for rdkcentral/meta-rdk-video 154

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: 418f095122797ee1e7db048a82877cbeba354d33
=> NO-TICKET - Auto PR for rdkcentral/meta-rdk 60

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 9dcec18ad3af4adde8ab493b0b6be9fb32d3d919
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 834399e3aef5a4b8e468df36eb27354c6ff0f8b8
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 834399e3aef5a4b8e468df36eb27354c6ff0f8b8
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 9dcec18ad3af4adde8ab493b0b6be9fb32d3d919
=> RDKEMW-3359 - Auto PR for rdkcentral/meta-rdk-video 160

middleware-generic.xml
Details: Reason for changes : making rdk-cert-config open-source 
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 3db2d023752a1b07d0f3c47578e0be2fa0e6c00c
=> RDK-56725 - Auto PR for rdkcentral/meta-middleware-generic-support 152

middleware-generic.xml
Reason for change : Auto merged NOT working
Signed-off-by: Ankur Adroja <Ankur_Adroja@comcast.com>
=> RDK-56725 : Manually added meta layer SHA

middleware-generic.xml
Details: Reason for change: Updated the recipe file of rdknativescript to include video.js rootfs
Test Procedure: build should be successful and video.js must be in rootfs
Risks: low
Priority: P2
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: e7c61664d44b6dbdf0c60ef95926b9499d44dc96
=> RDKEMW-2170 - Auto PR for rdkcentral/meta-rdk-video 170

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: e27de4ee1c3417e0c9c1d8f614967604afafcdc4
=> RDKEMW-3175 - Auto PR for rdkcentral/meta-rdk-video 140

middleware-generic.xml
Details: Reason for change:  update ctrlm tag for QA feature branch verification Test Procedure:
Risks:              Low
Change-Id: I5ebc6f6561e676840a4878d4d5cec8abbb80b4a9
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 455420d002fa49923e4f2a4533ef6d5fb427915e
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: f86fb2d807de97131bfce589d90432a2dab6ade8
=> RDKEMW-3276 - Auto PR for rdkcentral/meta-middleware-generic-support 137

middleware-generic.xml
Details: Reason for the changes: Added hal lib dependency in the meta layer
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 20bc199715c75c6721c53b936f41edbcd4f7572d
=> RDK-57140 - Auto PR for rdkcentral/meta-rdk-video 153

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 16e7d2c57e23e711d30b224af812ffcb2eb4a15d
=> RDKEMW-3476 - Auto PR for rdkcentral/meta-middleware-generic-support 204

middleware-generic.xml
Details: Reason for change: Optimization of javascriptcode lib
Test Procedure: build should be successful.
Risks: low
Priority: P2
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 40fa78d7849d1c89e3c28e5500a27b8036461c28
=> RDKEMW-3572 - Auto PR for rdkcentral/meta-rdk-video 179

middleware-generic.xml
Reason for change : Revision update Apr 07
Test Procedure : None
Priority : P1
Risks : None
Signed-off-by : snazee925@cable.comcast.com
=> RDKEMW-3265 : [MTK][MW] Rebase hg-bringup to latest develop - 07 April 2025

middleware-generic.xml
Details: Reason for change: Check Valid TTS Backend provided
Test Procedure: Mentioned in ticket
Risks: Low
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: e9826b829c6c3cddce657976861c86727e795d78
=> RDKEMW-3554 - Auto PR for rdkcentral/meta-middleware-generic-support 219

middleware-generic.xml
Details: Reason for change: Updated latest version of Rialto
Signed-off-by: Balasaraswathy_N <Balasaraswathy_N@comcast.com>
Priority: P1
Test Procedure: Validate Xumo Stream
Risks: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: c4ffec72eca729188f5b19ca67a5493686aef1fa
=> RDKEMW-3491 - Auto PR for rdkcentral/meta-middleware-generic-support 176

middleware-generic.xml
Set rdkcentral URL
Test Procedure: Make local VM build
Risks: Low
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 1c59d2928f74ff48a9c026cee87deec25cc93081
=> RDKEMW-3670 - Auto PR for rdkcentral/meta-rdk-video 207

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 1632bdc835ea3245df1b8db590fb44037fdd7c1d
=> RDKEMW-3623 - Auto PR for rdkcentral/meta-middleware-generic-support 236

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: d9475d66db9694a7875ad434a87849c0dabd0ddc
=> RDKEMW-3476 - Auto PR for rdkcentral/meta-middleware-generic-support 213

middleware-generic.xml
Details: RDKEMW-2808: RDKE/V User Settings Update Presentation language in Failure
Reason for change: RDKE/V User Settings Update Presentation language in Failure
Test Procedure: NA
Risks: NO
Priority: P1
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: f332e1d60f10a46058b86646b44665b12ef1baf1
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: aa7ae7021ef462b34504555a853473d55d3da282
=> RDKEMW-2808 - Auto PR for rdkcentral/meta-middleware-generic-support 227

middleware-generic.xml
Details: Reason For Change : 
Framework to parse bind configs and generate service dynamically
Consolidate Bind configurations
Test Procedure : Add bind configs and inherit the Framework in Package group
Signed-off-by : [Sindhuja_Muthukrishnan@comcast.com](mailto:Sindhuja_Muthukrishnan@comcast.com)
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 910b59cb00403748ceb545800393888465cc2a40
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: d016bba99b4dc5b0e56e10a39bb58ed1ea3bb09f
=> RDK-56570 - Auto PR for rdkcentral/meta-rdk 68

middleware-generic.xml
Details: Reason for change: Upgrade to new NetworkManager PLugin release - 0.15.0 with following bug fixes
* Memory leak is observed with Network Manager plugin
* Unable to Reconnect to WiFi using WPS -Screen stuck at Searching page
* Enable CLI Tool in NetworkManager-Plugin: Add Compile-Time Option for gdbus & resolve compilation error
Test Procedure: Please referred the ticket
Risks: Medium
Signed-off-by: Thamim Razith Abbas Ali <ThamimRazith_AbbasAli@comcast.com>
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: c8edc23db9d0cbc37ae93e772cb2e1a9057eb29e
=> RDKEMW-3682 - Auto PR for rdkcentral/meta-rdk-video 249

middleware-generic.xml
Details: Reason for change: Add COM-RPC support to Warehouse plugin 
Test Procedure: Test Warehouse - All APIs
Risks: Medium
Priority: P1
Signed-off-by:Dineshkumar P dinesh_kumar2@comcast.com
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: ee3676280e31223c7eef8343f0ecebb5c33ddeae
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: cb76062132bb9701ddaa4c534830ef08a3e56d6f
=> RDKEMW-1024 - Auto PR for rdkcentral/meta-middleware-generic-support 264

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 4716d4640d0944635ba97a5113d623471fd65072
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: b8fed50f9b360097c02faaa2df2a7f720092a48a
=> RDKEMW-2884 - Auto PR for rdkcentral/meta-rdk-video 190

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: c26977139bb8abe55da28ce06d9d4f8b223e2636
=> NO-TICKET - Auto PR for rdkcentral/meta-rdk 77

middleware-generic.xml
Details: RDK-57093: PowerManager Interface methods and event APIs modified
Reason for changes: The Interface method return type and event APIs are modified as per API spec
Test procedure: Full stack build
Risk: Low
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: f49e711836547f76b831ff79784cfccd4a74659a
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 20c15ef667cbf3af7b6cfa1d6a305d34cfe55f25
=> RDK-57093 - Auto PR for rdkcentral/meta-middleware-generic-support 283

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: cbf1bc722648c6cd29b0ee0c66ad5128ee2a36c3
=> RDK-51094 - Auto PR for rdkcentral/meta-middleware-generic-support 281

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 504e2a2d537f2ab281a4ecbcef8fd0477a4f108e
=> RDK-56121 - Auto PR for rdkcentral/meta-middleware-generic-support 289

middleware-generic.xml
Details: Reason for change: Release rdkfwupdater
Test Procedure: Basic Sanity, Focused regression
Risks: Low
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 7f7448a8cc98d60a27f8596f2f1ac0f0bed1041b
=> RDK-56120 - Auto PR for rdkcentral/meta-middleware-generic-support 272

middleware-generic.xml
Details: Updated rbus.bb with latest release 2.3.0
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: 9dd7b284156ba888181cb386c1414b5d33031cdb
=> NO-TICKET - Auto PR for rdkcentral/meta-rdk 79

middleware-generic.xml
Details: Reason for change: UsbPlugins documentation and middleware updates.
Test Procedure: Make full stack build and run Usb plugins curl commands.
https://etwiki.sys.comcast.net/pages/viewpage.action?spaceKey=RDKV&title=USB+Device
https://etwiki.sys.comcast.net/display/RDKV/USB+Mass+Storage
Risks: Medium
Priority: P1
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: bd2f25bda7899f18ddaa681c6e92bc4942981ada
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: b23b5bd6297c9083cde3be7f326b17ce43c63ba5
=> RDKEMW-2907 - Auto PR for rdkcentral/meta-middleware-generic-support 309

middleware-generic.xml
Details: Reason for change: Remove ir related middleware dependencies based on iarmmgrs-soc-realtek and iarmmgrs-soc-amlogic
Test Procedure: Build and verify
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: a6ae9da610a605731c00527cb6edbc20bcd775ad
=> RDKEMW-3775 - Auto PR for rdkcentral/meta-rdk-video 241

middleware-generic.xml
Details: Reason for change: Fix coverity issues in rdmagent
Test Procedure: Build RDKE image
Risks: Low
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 448a2e00cde655ad6f4f93cf60a6e6a317755c38
=> RDK-57075 - Auto PR for rdkcentral/meta-middleware-generic-support 313

middleware-generic.xml
Reason for change : Revision update Apr 28
Test Procedure : None
Priority : P1
Risks : None
Signed-off-by : [snazee925@cable.comcast.com](mailto:snazee925@cable.comcast.com)
=> RDKEMW-3857 : [MTK][MW] Rebase hg-bringup to latest develop - 28 April 2025

middleware-generic.xml
Details: Reason for change: Added Activating logs in COMRPC Requesting Plugins
Risks: High
Priority: P0
Signed-off-by: Thamim Razith tabbas651@cable.comcast.com
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 56942b7695ee0c13de697b5304aa41c99c11b4a9
=> RDKEMW-3263 - Auto PR for rdkcentral/meta-rdk-video 147

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: e26340669d59e890c81c545345203818743fe148
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 747d22207e15b8d299100dd4757a3c6723bef929
=> RDKEMW-3607 - Auto PR for rdkcentral/meta-rdk-video 203

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 7cf115ab883c6e07da35d32bf98d8100a6300e36
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: a5d872ff9b1509adeadc4e1bfd7b6782ce7aa760
=> RDKEMW-3545 - Auto PR for rdkcentral/meta-middleware-generic-support 324

middleware-generic.xml
Ensure rtk usa activation works fine
whoami enabled for maintance manager
Risks: Low
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 3d9754b7f821b10488f214bf1fe893caa59f2341
=> RDKEMW-3830 - Auto PR for rdkcentral/meta-rdk-video 281

middleware-generic.xml
Details: Update the latest SRCREV of tr69
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 06b05a9ec1ad4f00f7514454d489708fc2dcde8b
=> NO-TICKET - Auto PR for rdkcentral/meta-middleware-generic-support 331

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: a3ab6363b3c8f15a10f58950e207f05086d33173
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 7defd98fc092c785e8f0aa9666a93b8f1d645c4e
=> RDKEMW-1014 - Auto PR for rdkcentral/meta-rdk-video 274

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 0ac7c36259d34214ac252161117b18440b340363
=> RDKEMW-3911 - Auto PR for rdkcentral/meta-middleware-generic-support 327

middleware-generic.xml
Details: Reason for change: Subtec changes to build on ubuntu
Test Procedure: Check subtec builds and runs successfully on ubuntu, regression for subtec repo
Risks: Low
Signed-off-by:krithika_venkataraman@comcast.com
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: f1e3d3819d9af8e736069763639a7a0ef829e0a5
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 0ac7c36259d34214ac252161117b18440b340363
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: f1e3d3819d9af8e736069763639a7a0ef829e0a5
=> RDK-57126 - Auto PR for rdkcentral/meta-rdk-video 327

middleware-generic.xml
Details: Reason for change: Upgrade to new release - 0.16.0 with following Bug fixes
* Fixed the deregistration of Security Agent upon one successful WPS Connect.
* JSONRPC response for Ping in the legacy plugin is addressed
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: cc9b42198bed2ce23c6d77bdc972a6c23d1ef8f1
=> RDKEMW-3914 - Auto PR for rdkcentral/meta-rdk-video 317

middleware-generic.xml
Details: Reason for change: changed network manager version 0.17.0
Test Procedure: NA
Risks: Medium
Priority: P0
Signed-off-by: Gururaaja ESR <gururaja_erodesriranganramlingham@comcast.com>
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: e2163af927cd317e3626df832cbdc5019253cd40
=> RDKEMW-3086 - Auto PR for rdkcentral/meta-rdk-video 319

middleware-generic.xml
Details: Reason for change: Fix nplb build failure
Test procedure: Refer ticket
Risks: low
Priority: P2
Signed-off-by: Ansu Mathew <Ansu_Mathew@comcast.com>
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 96df0468edabea4ecce49497334f9af6064f0f50
=> PREMIUMAPP-3308 - Auto PR for rdkcentral/meta-rdk-video 322

middleware-generic.xml
Details: Reason for change: read make from MFR first and if not available fall back to device.properties.
Risks: None
Signed-off-by: ramkumar_prabaharan ramkumar_prabaharan@comcast.com
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: bfb5e659652fb00b2f747df231747534a76d2ab5
=> RDKEMW-2572 - Auto PR for rdkcentral/meta-rdk-video 320

middleware-generic.xml
Details: Reason for change: dsGetEdid2AllmSupport removal for hal header
Test Procedure: test purpose
Risks: Low
Priority: P1
Signed-off-by: bp-tdora114 [dautapankumar.dora@sky.uk](mailto:dautapankumar.dora@sky.uk)
https://ccp.sys.comcast.net/browse/RDKEVD-445
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 81e381079a412451ffe89649fe01330d6eee1e35
=> RDKEMW-4012 - Auto PR for rdkcentral/meta-middleware-generic-support 361

middleware-generic.xml
Details: update control component to 1.0.9
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: fddee3da25b705c59ebcab2c4cbe8b9bd02bd3aa
=> RDKEMW-3882 - Auto PR for rdkcentral/meta-middleware-generic-support 297

middleware-generic.xml
Details: Reason for change : Enabling libpackage with package manager and enabling it
Test Procedure: Package manager is getting activated with response OK
Risks: Medium
Priority: P2
Signed-off-by: Abhay Kant bp-akant305@cable.comcast.com
- Repository: rdkcentral/entservices-infra, Merge Commit SHA: f4ea56f78d9be5b335e056bbd3e624575ff7062b
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 94a9d79a72ec4465c79336dd1f45c71e573b337e
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 94a9d79a72ec4465c79336dd1f45c71e573b337e
=> RDKEMW-1741 - Auto PR for rdkcentral/meta-rdk-video 158

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 75554d617dbfbeba5c6f7e34436b5633ec8b8a9a
=> NO-TICKET - Auto PR for rdkcentral/meta-middleware-generic-support 371

middleware-generic.xml
Details: Reason for change: Added support for network metrics, updated rev
Test Procedure: build should be successful.
Risks: low
Priority: P2
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: f30b8fad32a0739277badd71a24cee43bc31df3d
=> RDKEMW-3105 - Auto PR for rdkcentral/meta-rdk-video 340

middleware-generic.xml
Details: Reason for change: read make from MFR first and if not available fall back to device.properties.
Risks: None
Signed-off-by: ramkumar_prabaharan <ramkumar_prabaharan@comcast.com>
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 913411f042058df0c22092b28f80cb21806d23e3
=> RDKEMW-2572 - Auto PR for rdkcentral/meta-middleware-generic-support 375

middleware-generic.xml
Details: Reason for change : Source commit & revision update for thunderstartupservices and rdkwindowmanager
Risks: Medium
Priority: P1
Signed-off-by: Abhay Kant bp-akant305@cable.comcast.com
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 52fcfe87d7dd5a0bb321c0d2230dc1a562c13e7b
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 1cf6d1bf6be36a517db46c3bb3af286e14d424f5
=> RDKEMW-2738 - Auto PR for rdkcentral/meta-rdk-video 371

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: ee3d2cec1e47b67339a5a1295f1a3249d4786c9c
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: f6a4c2df3baac9fea9fcc4da19f61bab4e1c9966
=> RDKEMW-3978 - Auto PR for rdkcentral/meta-middleware-generic-support 399

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: d1c5775c24230d9fc37181d334fb1743d06d4e87
=> RDKEMW-3746 - Auto PR for rdkcentral/meta-middleware-generic-support 389

middleware-generic.xml
Details: Reason for change: Use latest Dobby version  
Test Procedure: Check Dobby version using DobbyTool --version  
Signed-off-by: Karthick S <karthick_s@comcast.com>
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 13845d5f9a7dae952fa54d6baa183a33ef43570c
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: a5338543b0bffcb7be09680480ba408a73b0e11b
=> RDKEMW-4017 - Auto PR for rdkcentral/meta-middleware-generic-support 350

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: ca5621b09e712c24a5b048c088f3f7653b0bfec3
=> RDKEMW-3974 - Auto PR for rdkcentral/meta-rdk-video 321

middleware-generic.xml
Details: The System time mgr Power manager changes and Coverity Fixes in component
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 63fd27b85946a4b1db4b181bb3511fa263d47d27
=> RDK-56904 - Auto PR for rdkcentral/meta-middleware-generic-support 418

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 861384761c84ae392b8ea17dec16c6835d302209
=> RDKEMW-4153 - Auto PR for rdkcentral/meta-middleware-generic-support 415

middleware-generic.xml
Details: RDKEMW-4105: RDK-E Update MW Manifests OSS Release 4.6.0
Reason for change: 
RDK-E Update MW Manifests OSS Release 4.6.0
Risks: Low
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: fc22dabd5e4ba379b5970583d41e6bc84795c100
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: e5b8a478a3512bf45c808e435e8754940d9c0d9a
- Repository: rdkcentral/meta-rdk-halif-headers, Merge Commit SHA: e1bb3f85b14a56b9b1866b99da70a912206eaf8b
=> RDKEMW-4105 - Auto PR for rdkcentral/meta-middleware-generic-support 425

middleware-generic.xml
Details: Reason for change: Updated latest version of Rialto
Priority: P1
Test Procedure: Validate Xumo fast track channels
Risks: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: c7db11a79844c69eb7dc8866214474d21d0952d4
=> RDKEMW-4303 - Auto PR for rdkcentral/meta-middleware-generic-support 434

middleware-generic.xml
Details: Update sysint_git.bb
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: d11ab8e94b983573f53bcb45eec7e213ec8a0d24
=> RDKOSS-192 - Auto PR for rdkcentral/meta-rdk-video 416

middleware-generic.xml
Details: Reason for change: fetch failure in telemetry2_0
Test Procedure: Refer JIRA
Risks: Low
Priority: P0
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 4410c74673408e40e254588d0cab33d7ed5a0e17
=> RDKEMW-3401 - Auto PR for rdkcentral/meta-middleware-generic-support 438

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: f72e7b5e17681f91c30c27c1bb0b643f8394513f
=> NO-TICKET - Auto PR for rdkcentral/meta-middleware-generic-support 442

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 100580514ef6cfa52e5fc0d8f33bb889354790c3
=> NO-TICKET - Auto PR for rdkcentral/meta-rdk-video 417

middleware-generic.xml
Details: Update sysint_git.bb
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 19c565661f19d06183bf1b59d90727685744acd4
=> NO-TICKET - Auto PR for rdkcentral/meta-rdk-video 429

middleware-generic.xml
Details: Update rfc_git.bbappend
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 355e061d1818b7da76cb7e26a4cda82d31a255ba
=> RDKE-791 - Auto PR for rdkcentral/meta-rdk-video 399

middleware-generic.xml
Details: Updated RFC sha and revison
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 3dbcc00c063edd2e171bbc7206957f0904056c85
=> RDKE-791 - Auto PR for rdkcentral/meta-middleware-generic-support 464

middleware-generic.xml
Details: Reason for change: 1) Update OCDM Decrypt Thread name 2) Remove Thread priority setting from User space Test Procedure: Refer Ticket
Risks: Medium
Priority:P1
Signed-off-by: Krishna Priya Kanagaraj <Krishnapriya_kanagaraj@comcast.com>
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 11108eec62867b0418de1e37723f2d2edf43dd21
=> RDKEMW-4394 - Auto PR for rdkcentral/meta-rdk-video 454

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: ec791efc7fc75c6f53a8e7f17f67a22dbd2aa3a6
- Repository: rdkcentral/entservices-inputoutput, Merge Commit SHA: a46b1c9167fba19fd2359e60959197e99b2c855b
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 6e637dd56ec7d0a29655c160efe5169507506293
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: ec791efc7fc75c6f53a8e7f17f67a22dbd2aa3a6
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 6e637dd56ec7d0a29655c160efe5169507506293
=> RDK-52028 - Auto PR for rdkcentral/meta-rdk-video 467

middleware-generic.xml
Details: Update trace patch for nextline
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: d7fede9ea52c721c8b15fe0ce759ccbba7ca66ea
=> NO-TICKET - Auto PR for rdkcentral/meta-rdk-video 448

middleware-generic.xml
Details: Reason for change : Updating entservices-apis tag
Test Procedure: Thunder RPC based testing of setVisible plugin method
Risks: Low
Priority: P1
Signed-off-by: Siva Thandayuthapani [sithanda@synamedia.com](mailto:sithanda@synamedia)
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 972567525d18d5e2f1e3c3f8597da3e3816b65b3
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: bcf80ee9bf248114d6c8391828605b8deb85c335
=> RDKEMW-3813 - Auto PR for rdkcentral/meta-rdk-video 469

middleware-generic.xml
RDK-E Update MW Manifests OSS Release 4.6.0
Realtek release 7.0.0 support with oss 4.6.0
Risks: Low
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 14c1fc1a9cfedd0baf45501408ce5b73758942df
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: cefa4a8ba5e6683a0916c2b971d8046d13e5ca7f
- Repository: rdkcentral/meta-rdk-halif-headers, Merge Commit SHA: 2b92724994a17e00004d208d8f56cc19dddb340a
=> RDKEMW-4105 - Auto PR for rdkcentral/meta-middleware-generic-support 463

middleware-generic.xml
Details: Added release update for sysint as 2.0.1
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: feeb8b25fb2ebb132c550a2e1deb0341d1e8bee7
=> RDKTV-36569 - Auto PR for rdkcentral/meta-middleware-generic-support 480

middleware-generic.xml
Details: Reason for change: Upgrade to new release - 0.18.0 with following Bug fixes
- Fix for onDefaultInterfaceChange event is posted empty
- The interval between the ping requests is reduced
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: ea75d26d6c2bc087deb085e0bfc014ec12f07c20
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 4cfa5eceb041e0507712727c0b385982ee1622dd
=> RDKEMW-4215 - Auto PR for rdkcentral/meta-rdk-video 492

middleware-generic.xml
Details: Reason for change: Enhancement to Thunder Hang Detector
Test Procedure: verify with the thunder hang detector RFC
Risks: Medium
Priority: P2
Signed-off-by: Gururaaja ESR <gururaja_erodesriranganramlingham@comcast.com>
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: fd048bbc1ae8b3ce42dde4492362c23897afbc29
=> RDKEMW-2852 - Auto PR for rdkcentral/meta-rdk-video 443

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: ebdec7c89bf1a35929b7793cae7089f6b339cefd
=> RDK-56852 - Auto PR for rdkcentral/meta-rdk 96

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 12fe813b106226c9c7a62e0ee059fab1041153bd
=> RDKEMW-4377 - Auto PR for rdkcentral/meta-rdk-video 437

middleware-generic.xml
Reason for Change: Includes these fixes RDKEMW-4220, RDKEMW-4393, RDKEMW-3311, RDKEMW-4220
=> RDK7RM-51, RDK7RM-44, RDK7RM-50, RDK7RM-51, RDK7RM-45, RDK7RM-59, RDK7RM-43, RDK7RM-46: RDK7 hotfixes

middleware-generic.xml
Details: Reason for change: bringup meta-sharp-m120 layer
Risks: Low
Priority: P1
Signed-off-by:mkooda197@cable.comcast.com
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: 8d2065186d5348712227ea8b884fcbddd58afcf5
=> RDKEMW-4428 - Auto PR for rdkcentral/meta-rdk 97

middleware-generic.xml
Details: …sting
Reason for change: Cleanup and remove pwrmgr references from entservices-casting Test Procedure: build
Risks: Medium
Signed-off-by:gsanto722 grandhi_santoshkumar@comcast.com
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 0f9c952169a4bb00489147112329596522f55e39
=> RDKEMW-4204 - Auto PR for rdkcentral/meta-rdk-video 521

middleware-generic.xml
Details: Reason for change: Bring-up changes of DELIA-66969 into RDKE.
Test Procedure: Build and validate crash
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: d4c3150a82b706767ab6b3a78ecf92a57f200897
=> RDKEMW-4445 - Auto PR for rdkcentral/meta-rdk-video 439

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 260f8dd7320caf8bcca5936227acfa9db2f6d091
=> RDK-56123 - Auto PR for rdkcentral/meta-middleware-generic-support 532

middleware-generic.xml
Details: Reason for change: Add COM-RPC support to LEDControl plugin Test Procedure: Test LEDControl - All APIs
Risks: Medium
Priority: P1
Signed-off-by:Dineshkumar P dinesh_kumar2@comcast.com
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: a98dd0dd2fa3fe09b18759f338218c7997718107
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: f09d0eb8c05c25ff0047713cd98ef9482651f45c
=> RDKEMW-1016 - Auto PR for rdkcentral/meta-middleware-generic-support 541

middleware-generic.xml
Details: Reason for change : Disable Sky appsserviced services
Test Procedure: Sky service is getting stopped and ai manager plugins are getting activated
Risks: Medium
Priority: P2
Signed-off-by: Dali Hariharan bp-dharih957@cable.comcast.com
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 9889b438502984c4842a35f9bb204f7203bd5cbf
=> RDKEMW-4213 - Auto PR for rdkcentral/meta-middleware-generic-support 517

middleware-generic.xml
Details: Reason for change: Updated the Callsign and correct the return logs
Test Procedure: please referred from the ticket
Risks: Medium
Signed-off-by: Thamim Razith <ThamimRazith_AbbasAli@comcast.com>
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 9bf8085b0e95dcafa6e86dd7dc358aa433ee5df5
=> RDKEMW-4182 - Auto PR for rdkcentral/meta-rdk-video 557

middleware-generic.xml
Details: Reason for change: Upgrade to new release - 0.19.0 with following Bug fixes
- Fixed Persistence related to interface enable/disable status
- Added addtional logs to understand WIFISignal monitoring thread
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 2f5903f826e1449a0a0e167711ebce37f8b046b9
=> RDKEMW-4100 - Auto PR for rdkcentral/meta-rdk-video 560

middleware-generic.xml
Details: Reason for change:Update manifest
Test Procedure: Build and verify
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: cd1f87b04849bafa0e4dc2bdadd3bc55df0dfb1f
=> RDKEMW-4577 - Auto PR for rdkcentral/meta-middleware-generic-support 537

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 1c4ebf1dbb4709e722b5479abb52f6e0ea22cdda
=> RDKEMW-3421 - Auto PR for rdkcentral/meta-middleware-generic-support 395

middleware-generic.xml
Details: …- MW Generic
RDKEMW-4197: Dependency Removal of the powermanager from systimemgr …
- Repository: rdkcentral/systemtimemgr, Merge Commit SHA: 56b8613ad3be2070a822fd045fd1e0497c07b952
- Repository: rdkcentral/systemtimemgr, Merge Commit SHA: 56b8613ad3be2070a822fd045fd1e0497c07b952
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 35cc5e285844eab8b5dd2dedc2ee294b091cd014
- Repository: rdkcentral/systemtimemgr, Merge Commit SHA: 56b8613ad3be2070a822fd045fd1e0497c07b952
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 35cc5e285844eab8b5dd2dedc2ee294b091cd014
- Repository: rdkcentral/systemtimemgr, Merge Commit SHA: 56b8613ad3be2070a822fd045fd1e0497c07b952
- Repository: …
=> RDKEMW-4197 - Auto PR for rdkcentral/systemtimemgr 578

middleware-generic.xml
Details: ctrlm 1.0.10 release for rdkcentral (ctrlm-main and xr-voice-sdk..
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: f7a3e6ad6f46e96ad5172d3e4f230e70a8cae112
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: f7a3e6ad6f46e96ad5172d3e4f230e70a8cae112
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: f7a3e6ad6f46e96ad5172d3e4f230e70a8cae112
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: f7a3e6ad6f46e96ad5172d3e4f230e70a8cae112
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: f7a3e6ad6f46e96ad5172d3e4f230e70a8cae112
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: …
=> RDKEMW-4424 - Auto PR for rdkcentral/meta-middleware-generic-support 585

middleware-generic.xml
Details: Reason for change: Removed the script in order to add it as part of xumo TV specific layer.
Test Procedure: The functionality should work as before.
Priority: P1   
Risks: Medium
Signed-off-by: Faizal Hasan.Z <faizalhasan_zahirhussain@comcast.com>
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 7c14bfd34f584aa9688ea6aad7c707992e83ed9d
=> RDKEMW-4622 - Auto PR for rdkcentral/meta-rdk-video 587

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 638c5a9736ec7a4f16626d40c1861489ba350067
=> RDKEMW-3036 - Auto PR for rdkcentral/meta-rdk-video 53

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: c5134a8754362a1d88665acb99a9b36ba78d4064
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: fadf0e665ae35bd3f8a24ac408f955e878ef002a
=> RDKEMW-4872 - Auto PR for rdkcentral/meta-rdk-video 616

middleware-generic.xml
Details: Reason for change: Removed the WPEFrameworkSecurity agent Utility
Risks: Medium
Priority: P1
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 24fdc063de6c9041fdee7be94a861da118143f6d
- Repository: rdkcentral/entservices-infra, Merge Commit SHA: 68d2e4e74c602022cf57ceeee2386cab0b438636
- Repository: rdkcentral/entservices-softwareupdate, Merge Commit SHA: 3afce7fe3a68bce2e68b9cf7a430741a7d40a9bb
- Repository: rdkcentral/entservices-infra, Merge Commit SHA: 68d2e4e74c602022cf57ceeee2386cab0b438636
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 24fdc063de6c9041fdee7be94a861da118143f6d
- Repository: rdkcentral/entservices-softwareupdate, Merge Commit SHA: …
=> RDKEMW-2278 - Auto PR for rdkcentral/meta-rdk-video 220

middleware-generic.xml
Details: Reason for change: [AAMP] 2.4.3 Tag update with bug fixes Test Procedure:
Priority: P2
Risks:Low
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 7e48629f66b4a6d51dc99e71a486e9bdfe289c3d
=> RDKEMW-5062 - Auto PR for rdkcentral/meta-middleware-generic-support 605

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 1312f5d31df6b3092ad68b7a8c42a24c3484429a
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 769481a45a442897af61d1ae397f2e37182e391e
=> RDKEMW-5144 - Auto PR for rdkcentral/meta-rdk-video 638

middleware-generic.xml
Details: Reason for change: Error handling in case session is invalid Test Procedure: Validate Netflix playback
Risks: Medium
Priority:P1
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: e465f76bf99a64a72e206b97d1babf51a31260e3
=> DELIA-68179 - Auto PR for rdkcentral/meta-rdk-video 602

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 72535e95090ad466b7ab222dd3d36cc30c5dc796
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 2923164ce4f5ba14e25454bfc1a8ec54d54c5074
=> RDKEMW-5190 - Auto PR for rdkcentral/meta-rdk-video 658

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 6fe4d23a89ca0c6e973acbcafeb8a0b5ab0fcf1e
=> RDK-56578 - Auto PR for rdkcentral/meta-rdk-video 250

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 401361aa1cbc279b3a97ff8f13c8f8299a3702d1
=> RDKEMW-5124 - Auto PR for rdkcentral/meta-middleware-generic-support 635

middleware-generic.xml
Details: Reason for change: Return an error message for firmware upto date validation
Test Procedure: verify build success and basic test
Risks: Low
Priority: P1
Signed-off-by: ramkumar_prabaharan@comcast.com
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 30c3a7c6e6044a53294442e4439d32f213b2ac9b
=> RDKEMW-4719 - Auto PR for rdkcentral/meta-rdk-video 563

middleware-generic.xml
Details: Reason for change: Cobalt 25 maintenance
Test Procedure: N/A
Risks: None
Change-Id: I4ffd94c08fb58a9fbe496f2cc6221a99032d1856
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: ef3cdd874db1bc99beda6a2cbb79117abf8e5202
=> RDKEMW-5327 - Auto PR for rdkcentral/meta-rdk-video 720

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: e3fee65e0a76217f78afaa5f17fc6e661fa72eb3
=> RDKEMW-1012 - Auto PR for rdkcentral/meta-rdk-video 723

middleware-generic.xml
Details: Reason for Change: Added COM-RPC support to SharedStorage plugin 
Test Procedure: Test- All SharedStorage plugin APIs Risks: Low
Priority: P1
Signed-off-by:Dineshkumar P [dinesh_kumar2@comcast.com]
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 896d29d867095d7eed4f30c555daddbdd926a367
=> RDKEMW-1021 - Auto PR for rdkcentral/meta-middleware-generic-support 677

middleware-generic.xml
Details: ctrlm release v1.1.0, ctrlm-irdb-hal release v1.1.0
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 8d71f22f57bd1365145143b7b85f18a4a8c83329
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 74cf3bc2e91ac17e4949dcef9f2599e67b1a8b29
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 8d71f22f57bd1365145143b7b85f18a4a8c83329
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 74cf3bc2e91ac17e4949dcef9f2599e67b1a8b29
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 8d71f22f57bd1365145143b7b85f18a4a8c83329
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 74cf3bc2e91ac17e4949dcef9f2599e67b1a8b29
=> RDKEMW-4793 - Auto PR for rdkcentral/meta-middleware-generic-support 589

middleware-generic.xml
Details: Update recipe to remove RF4CE enable flag
- Repository: rdkcentral/control, Merge Commit SHA: 3d4b89e974ba7580a4e8a9d4843b52d41f281bd2
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 74cf3bc2e91ac17e4949dcef9f2599e67b1a8b29
=> RDKEMW-3798 - Auto PR for rdkcentral/meta-middleware-generic-support 456

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: b27f70ad3e5b58253a30832f472cdc58cc1f5a7c
=> NO-TICKET - Auto PR for rdkcentral/meta-middleware-generic-support 694

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: bf3bd0728e957cdccce0a66369726a6a80469ede
=> RDKEMW-5070 - Auto PR for rdkcentral/meta-rdk-video 698

middleware-generic.xml
Details: 
Reason for change: update sha and revision for rdklogger
Test Procedure: Build and verify
Risks: Medium
Priority: P0
Signed-off-by: navihansi@gmail.com
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: 82c4925fa4b96739692728abf21a7722446573ba
=> RDKEMW-5366 - Auto PR for rdkcentral/meta-rdk 124

middleware-generic.xml
Details: Update the package-version for entservices-apis and entservices-deviceanddisplay recipe.
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 321927acf9bf02ad44b8dee00fe211ffdc279b80
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 674b19d6268fd36d0d4fd6f0b481f775697fc43e
=> RDKEMW-5139 - Auto PR for rdkcentral/meta-rdk-video 746

middleware-generic.xml
Details: Reason for change: Return an error message for firmware upto date validation
Test Procedure: verify build success and basic test
Risks: Low
Priority: P1
Signed-off-by: [ramkumar_prabaharan@comcast.com](mailto:ramkumar_prabaharan@comcast.com)
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 5fa83f9a284c2a75a058be8ea0d2c9af1184ce3a
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: b5ff9116980f2fd7cb0b168b7b242829e3762674
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 5fa83f9a284c2a75a058be8ea0d2c9af1184ce3a
=> RDKEMW-4719 - Auto PR for rdkcentral/meta-rdk-video 756

middleware-generic.xml
Details: Update rbus to v2.5.0
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: 3ea7329353303fcc8780eed72860823fee402971
=> NO-TICKET - Auto PR for rdkcentral/meta-rdk 128

middleware-generic.xml
Details: Reason for Change: Updated entservices-infra to 1.4.5
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: edf6ced6a37075ffe18032ae1ea5e35ca6d1240c
=> RDK-57197 - Auto PR for rdkcentral/meta-rdk-video 789

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 111281932d4df1e25c55cf787f5d12c4a6b6be6d
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: cf1a53446b62e374da0f1ad4eb7fedc4bf093438
=> RDK-55149 - Auto PR for rdkcentral/meta-rdk-video 740

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 16f90c46df89dcccf4c7148a4ec62064ac01ae9e
=> RDKEMW-5467 - Auto PR for rdkcentral/meta-middleware-generic-support 736

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 1e94aeb281a00c5469363b2602105406a50cdbf5
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: bff85cdc87fd0da1bf686556b38738ff04a5f43f
=> RDKEMW-4812 - Auto PR for rdkcentral/meta-rdk-video 696

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 985b37f452752499fbaed85e0a1218d47f5cbf21
=> RDKEMW-2580 - Auto PR for rdkcentral/meta-rdk-video 811

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 86e42c95d41f1b35d8b407a77ddd01b75e2610b9
=> RDK-57914 - Auto PR for rdkcentral/meta-rdk-video 847

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 7f9da698d5b51482d1fd83e06b7850b618bc2773
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 25b947f5e99728f07e6b81e3d72bd7dddc75bb64
=> RDKEMW-5167 - Auto PR for rdkcentral/meta-rdk-video 804

middleware-generic.xml
Details: Reason for change : Reference to invalid file in packagemanager service
Test Procedure: Acivation of AppManager,LifecycleManager and PackageManager are tested
Risks: Medium
Priority: P1
Signed-off-by: Dali Hariharan bp-dharih957@cable.comcast.com
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 8b632208beabc0fa5a624be1308b2dbd220820ad
=> RDKEMW-5299 - Auto PR for rdkcentral/meta-middleware-generic-support 713

middleware-generic.xml
Test Procedure:
Risks:              Low
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: d932c3a5d70dbb867913c0fb8cf9c3156ac9798b
=> RDKEMW-4913 - Auto PR for rdkcentral/meta-middleware-generic-support 775

middleware-generic.xml
Details: Add the SHA and PV update for middleware
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: f6d57aebcd211f0db07d2cc5d621df9726d04d24
=> RDK-57987 - Auto PR for rdkcentral/meta-middleware-generic-support 843

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 178840945ea00d0d607caf2d63644b681866d647
=> RDKEMW-2865 - Auto PR for rdkcentral/meta-rdk-video 603

middleware-generic.xml
Details: JIRA ticket related to this changes is https://ccp.sys.comcast.net/browse/RDKEMW-5510
Test results can be found here: 
https://ccp.sys.comcast.net/browse/RDKEMW-5510?focusedId=22569576&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22569576
Corresponding vendor changes were earlier merged and the details can be found here:
Tvsettings HAL
[RDKTV-33767: Remove ODM specific apis - phase2 by arjun-binu_comcast · Pull Request #17 · rdk-e/tvsettings-soc-amlogic](https://github.com/rdk-e/tvsettings-soc-amlogic/pull/17)
Meta PRs:
[RDKTV-33767: ODM specific apis removal in tvsettings-hal by arjun-binu_comcast · Pull Request #571 · rdk-e/meta-rdk-vendor-oem-sky-amlogic-common](https://github.com/rdk-e/meta-rdk-vendor-oem-sky-amlogic-common/pull/571) …
=> RDKEMW-5510 - Auto PR for rdkcentral/meta-rdk-video 870

middleware-generic.xml
Details: Reason for change: Removed the WPEFrameworkSecurity agent Utility
Risks: Medium
Priority: P1
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 6ca6b653f24ec7b2c04276f1a465dab47b2ddf79
=> RDKEMW-2278 - Auto PR for rdkcentral/meta-rdk-video 641

middleware-generic.xml
Details: Reason for change: Remove Bind/Named from RDKE stack
Test Procedure: Basic sanity
Risks: Low
Signed-off-by: Abhinav P V [Abhinav_Valappil@comcast.com](mailto:Abhinav_Valappil@comcast.com)
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 0914baaf8e02da0d774ffd09637ce5a1f52f5d02
=> RDKEMW-5355 - Auto PR for rdkcentral/meta-middleware-generic-support 840

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: e5f035236b2fdff07597242fb84351430a638b1c
=> RDKEMW-4487 - Auto PR for rdkcentral/meta-middleware-generic-support 901

middleware-generic.xml
Details: Reason for change: Remove duplicate files
Test Procedure: Build RDKE image
Risks: Low
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: ad53e52a9774dedadacfe732ff2f1e1bb67b2152
=> XIONE-17419 - Auto PR for rdkcentral/meta-rdk-video 924

middleware-generic.xml
Details: Reason for change: Upgrade to new release - 0.21.0 with following Bug fixes
- Fixed WiFi On/Off toggling failure
- Fixed the bug in IPAddress availability check upon wake-up
- Removed the SetPrimartInterface method
- Added input param validation for Ping and Stun methods
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 76669f6c9e5bded91aea05d6e1cd0734d4b3ff41
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: d166393bea3ef4b4bf25d685b25e2f92d981375c
=> RDKEMW-5550 - Auto PR for rdkcentral/meta-rdk-video 962

middleware-generic.xml
Details: 
Rename the current clearDB() method into clearDBEnd().
Keep the current clearDB() call int the existing position
Call clearDBEnd() at the end in the processXconfResponseConfigDataPart
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 1f44ea1e5599983bc9911ccfb2d58bd628545283
=> RDKEMW-5675 - Auto PR for rdkcentral/meta-middleware-generic-support 896

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: dbd1598d4c6974b1006c98158114ec04b2c69483
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 720a2b5928e02e61a0c08326d434231c6a77a14f
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 720a2b5928e02e61a0c08326d434231c6a77a14f
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: dbd1598d4c6974b1006c98158114ec04b2c69483
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: dbd1598d4c6974b1006c98158114ec04b2c69483
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 720a2b5928e02e61a0c08326d434231c6a77a14f
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: …
=> RDKEMW-5072 - Auto PR for rdkcentral/meta-rdk-video 970

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: d3b9185ad832e0e536c2bf2a637d3b7faf4fdc2c
=> RDKEMW-3904 - Auto PR for rdkcentral/meta-rdk-video 751

middleware-generic.xml
Details: Reason for change: Upgrade wpe-backend-rdk to 0.5 and add libmanette patches
Test Procedure: refer ticket
Risks: NA
Priority: P0
Signed-off-by: Ganesh prasad Sahu GaneshPrasad_Sahu@comcast.com
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: 7c37b9fabf84167d62eaec66a30ff621be2440e3
- Repository: rdkcentral/rdke-common-config, Merge Commit SHA: 4dde7c49e403639b6e9b78a1e4f557fe73e34d4d
=> RDKEMW-749 - Auto PR for rdkcentral/meta-rdk 119

middleware-generic.xml
Details: Reason for change: pulled entservices-deviceanddisplay (3.1.1) and entservices-intputoutput(1.3.3)
Risks: Medium
Priority: P1
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 875f8a58f6ae99eff142d1305cb5755b34a11857
=> RDKEMW-3750 - Auto PR for rdkcentral/meta-rdk-video 1000

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 4157784503e15c246b9654b2b0c5476da515767e
- Repository: rdkcentral/sysint, Merge Commit SHA: 2ab7dbcdd33883cea3e442eb4d592269c9a648d1
=> RDKEMW-5573 - Auto PR for rdkcentral/meta-rdk-video 995

middleware-generic.xml
Details: Reason for change: Upgrade to new release - 0.22.0 with following Bug fixes
- Fixed trigger point for the connectivity monitoring
- Posting onWiFiStateChange Event when link-up for wifi event is received.
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: a364dd9611c4a3260cc11d877b3cb577adaeea60
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: d59b994d34a7a049867a7dc739f2620d8e42789a
=> RDKEMW-6063 - Auto PR for rdkcentral/meta-rdk-video 1031

middleware-generic.xml
Details: Reason for change: increase wait time for OCDM service to auto-start
Test Procedure: delay provisioning to more than 100 OCDM startup attempts
Implements: updates to wpeframework-ocdm.service
Risks: No
Source: COMCAST
License: Apache-2.0
Upstream-Status: Pending
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 1230d089ff69f4b8871d2c6c21e4c4d8f25585a4
=> RDKEMW-5207 - Auto PR for rdkcentral/meta-middleware-generic-support 1006

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: 42843dd7ca3daa870f4e303104465c57d328b311
=> NO-TICKET - Auto PR for rdkcentral/meta-rdk 162

middleware-generic.xml
Details: Updated latest revision patch set for RFC module
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 249f0006433a9d4655798857f8caed30cf874341
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: b71565019861e6395bde2a7e5e1fb9c3e29759a6
=> RDKEMW-5971 - Auto PR for rdkcentral/meta-middleware-generic-support 1041

middleware-generic.xml
Details: Reason for change: copying modules to recipe-sysroot
Test Procedure: build should be successful.
Risks: low
Priority: P2
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 4aa11db9882bae713aecbdcc6be6180b3393812b
=> RDKEMW-5230 - Auto PR for rdkcentral/meta-rdk-video 1147

middleware-generic.xml
Middleware CI manifests with the common us tv config
premerge CI for element. Add meta-image-assembler for uniform build job
Risks: Low
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: df63daf1f8f1e44607c8b881a5a86dfd20180e4f
=> RDKEMW-3037 - Auto PR for rdkcentral/meta-rdk 167

middleware-generic.xml
Details: Reason for change: Loading Apparmor profiles efficiently during boot-up.
Test Procedure: Ensure profiles are loading in expected mode.
Risks: low
Signed-off-by: ldonth501 <LasyaPrakarsha_DonthiVenkata@comcast.com>
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: bd5ac1cc29c803189eb12b20659618831806e327
=> RDKEMW-4903 - Auto PR for rdkcentral/meta-middleware-generic-support 1049

middleware-generic.xml
=> RDK-57964 : Update generic manifest

middleware-generic.xml
Details: Update latest SHA and PR in middleware
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 8fde23adfbb657f758ebd0ce6193f54c901c07c1
=> RDK-58526 - Auto PR for rdkcentral/meta-middleware-generic-support 1057

middleware-generic.xml
Details: RDKEMW-5739: Update SRCREV for entservices-peripherals
Signed-off-by: yuvaramachandran_gurusamy <yuvaramachandran_gurusamy@comcast.com>
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: a089180e9654e4cd6642bcbcaf63aa998331fd59
=> RDKEMW-5739 - Auto PR for rdkcentral/meta-rdk-video 1159

middleware-generic.xml
Details: Risks: None
Priority: P2
Signed-off-by: Ankur Adroja <Ankur_Adroja@comcast.com>
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: be1a104885a1ba90f0ed052a3e9e1892101a01e7
=> RDKEMW-6251 - Auto PR for rdkcentral/meta-middleware-generic-support 1054

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 227f0277c29b1fd4d431662f6f017bbb7c7414ba
=> RDKEMW-6310 - Auto PR for rdkcentral/meta-middleware-generic-support 1073

middleware-generic.xml
Details: RDKEMW-6230: Update pkgrev and srcrev for HdmiCecSink changes
Signed-off-by: yuvaramachandran_gurusamy <yuvaramachandran_gurusamy@comcast.com>
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: ef64bc64636dc0f536d2d3377bdd8b9e7ab3382e
=> RDKEMW-6230 - Auto PR for rdkcentral/meta-rdk-video 1180

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 6022fda057f3f958f3055e36f9337b87d235beb9
=> RDKEMW-5480 - Auto PR for rdkcentral/meta-rdk-video 1178

middleware-generic.xml
Details: Reason for change: Updated the meta layer tag with changes from RDKEMW-4590 
Test Procedure: Test the Warehouse Reset API
Risks: Low
Priority: P1
Signed-off-by:Dineshkumar P dinesh_kumar2@comcast.com
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: e11a5a9d12b2e6046671aecba5c77d562d563098
=> RDKEMW-4590 - Auto PR for rdkcentral/meta-rdk-video 1209

middleware-generic.xml
Details: Reason for change: Logging the milestone for WPE_FRAMEWORK_START.
Test Procedure: Boot the TV and collect systemd analyze.
Risks: low
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 24a749fd3098ae9608ddfd419df878a5ad1eab5c
=> RDKEMW-4404 - Auto PR for rdkcentral/meta-rdk-video 1205

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: a5a2a89c1b0290758ce32f8a02d3e583d92ccda7
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 88410946748bef8b31af4f16dce94a9c335079b9
=> RDKEMW-6132 - Auto PR for rdkcentral/meta-rdk-video 1256

middleware-generic.xml
Details: Reason for change: Update the rbus branch
Test Procedure: Verify Sanity
Risks: Medium
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: aa8f880c20e164e693c4256fcefa45938223dc2d
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: b605234cbbcdda8ad20caf3d0ab8419a6c108291
=> RDKEMW-6474 - Auto PR for rdkcentral/meta-rdk 184

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 5b29e501c6db078e350c5608d3b7259273132f85
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: 01c3e34ffb30be25c47ee63e134fdf64538a94af
=> RDK-57910 - Auto PR for rdkcentral/meta-middleware-generic-support 905

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: e88b326adfe16474891cd4980ff8cd41fef01396
=> RDKEMW-6145 - Auto PR for rdkcentral/meta-rdk-video 1190

middleware-generic.xml
Details: Reason for change: Upgrade to new release - 0.23.0 with following Bug fixes
- Added L1/L2 workflow for LegacyNetwork, LegacyWiFi and NetworkManager Plugins
- Fixed RemoveKnownSSID method to handle the invalid inputs
- Fixed the logging in GetIPSettings
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 265fa7301c71b89aa6b25ed33a436468481b43e7
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: b3e33ce3f06759dfbc139221b24bec31adee77df
=> RDKEMW-6189 - Auto PR for rdkcentral/meta-rdk-video 1275

middleware-generic.xml
Details: Reason for change: Latest version of gst-svp-ext provides a new API to pre-allocate secure memory.
Test Procedure: Verify encrypted playback across all apps on all platforms
Priority: P0
Risks: High
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: d50b4b50b58d554811a74bc62fa91b8eea4e833a
=> RDKEMW-2303 - Auto PR for rdkcentral/meta-rdk-video 1215

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 2e3331ba09b529bf3d139a2b9cd12c022f67c917
=> NO-TICKET - Auto PR for rdkcentral/meta-middleware-generic-support 1138

middleware-generic.xml
Details: Reason for change : onAppLaunchRequest and onAppUnloaded event implemented
Test Procedure: onAppLaunchRequest and onAppUnloaded event
Risks: Medium
Priority: P1
Signed-off-by: Dali Hariharan [bp-dharih957@cable.comcast.com](mailto:bp-dharih957@cable.comcast.com)
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: c30019a873a9c574457d28f31d8e5869f281f0fb
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: ad66434362237dea909e4889a36c38117cecfa9b
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: c30019a873a9c574457d28f31d8e5869f281f0fb
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: ad66434362237dea909e4889a36c38117cecfa9b
=> RDKEMW-5422 - Auto PR for rdkcentral/meta-rdk-video 1287

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: a8f3cac2c2060317a3040ea17b4eb160ee32bac6
=> RDKEMW-4643 - Auto PR for rdkcentral/meta-middleware-generic-support 1168

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: a98b1f749fcca53697f354fa3cb1d5be99894b8b
=> RDKEMW-6466 - Auto PR for rdkcentral/meta-rdk-video 1281

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: b1decaa3d109e8801dad3ae6eaeda4257ea3fe18
=> RDKEMW-6875 - Auto PR for rdkcentral/meta-rdk-video 1343

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: f18c8f3b4e6e62e712f066bff99eb163eb81c265
=> RDKEMW-6875 - Auto PR for rdkcentral/meta-middleware-generic-support 1218

middleware-generic.xml
Details: Change-Id: I0e599ef5c70337ca155c1731c5a4d7ccdc1037cf
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: a60f160e459c4fadd04ef949cf535ea01da81755
=> RDKEMW-6566 - Auto PR for rdkcentral/meta-middleware-generic-support 1229

middleware-generic.xml
Details: Reason for change: To have single version of rdklogger across RDKB, RDKV & RDKE
Test Procedure: Tested and verified
Risks: Medium
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: b2cc58a8291fde741528cf5547534e258c6ff8f0
=> RDKEMW-6709 - Auto PR for rdkcentral/meta-rdk 199

middleware-generic.xml
Details: RDKEMW-5927: Update pkgrev for xdial and entservices-casting
Signed-off-by: yuvaramachandran_gurusamy [yuvaramachandran_gurusamy@comcast.com]
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 446cdfe2bf2c1d1d86e287a46363ecbc178ad58d
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: ccde0abd376c3153745dfd0804e285ab12cdcabe
=> RDKEMW-5927 - Auto PR for rdkcentral/meta-rdk-video 1321

middleware-generic.xml
Details: Reason for change: update sysinst srcrev
Test Procedure: Flash the build , ssh and verify
Risks: High
Priority: P1
- Repository: rdkcentral/sysint, Merge Commit SHA: 8e21d5bfb1a0ceb68632e95dae7d58c471028a2f
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 802e93aaa661baa9403fad9b01108d3d9dea8fb5
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 802e93aaa661baa9403fad9b01108d3d9dea8fb5
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 802e93aaa661baa9403fad9b01108d3d9dea8fb5
=> RDK-57745 - Auto PR for rdkcentral/sysint 1299

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 6164501e6c1bb84e7592441fd01d1b0d4e297f98
=> NO-TICKET - Auto PR for rdkcentral/meta-middleware-generic-support 1308

middleware-generic.xml
Details: RDK-58233 : Cleaning up rdnss service
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: bbb1f3292afb4c87ab08a1b5e0a339698e80b878
=> NO-TICKET - Auto PR for rdkcentral/meta-rdk-video 1427

middleware-generic.xml
Details: Reason for change: sync the bluetooth changes
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: f52d0ef6d0ac70f2fab5d27659bc8363e6baa8b6
=> DELIA-68646 - Auto PR for rdkcentral/meta-rdk 217

middleware-generic.xml
Details: Reverts rdkcentral/meta-rdk#217
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: b3961d6bd17b01ded106e75dfaccea3dab3ddffd
=> DELIA-68646 - Auto PR for rdkcentral/meta-rdk 223

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: a9b0056fe380a70879cd69eccc94ef37cc804c62
=> DELIA-68646 - Auto PR for rdkcentral/meta-middleware-generic-support 1347

middleware-generic.xml
Details: Reverts rdkcentral/meta-rdk#223
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: ac533b78be69ab16cffa8d6c77bb73e932e2a9c9
=> DELIA-68646 - Auto PR for rdkcentral/meta-rdk 226

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 48d993b522cb0c93957fc2be90773f40f383a44f
=> RDKEMW-124 - Auto PR for rdkcentral/meta-rdk-video 1479

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 6b333a931b2d21661d87dc96795411aa5fc53ee6
=> RDKEMW-7541 - Auto PR for rdkcentral/meta-middleware-generic-support 1369

middleware-generic.xml
Details: # Key changes:
- AckController refactored with WorkerPool
- Thread-safety fixes in ThermalController
- Improved deep sleep wakeup logic
- Robust client callback handling.
- Deepsleep timer wakeup
- Deepsleep user wakeup with multiple keys
- NetworkStandbyMode change via curl
- WakeupSrcMask change via curl
- Restart of tr69 / dsmgr
Risks: Low
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: d6e573c91a4deba07a13ed88883fccbbead85432
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 0fce40561549f67c442635a272e62092c753236b
=> RDKEMW-6451 - Auto PR for rdkcentral/meta-rdk-video 1456

middleware-generic.xml
Details: Reason for change: Logrotate should run as a oneshot service to prevent memory issues over long uptime.
Test Procedure: Build RDKE image and check logrotate functionality
Risks: Low
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: c9016de27a79593cd509ef53a669312cdabc09ba
=> RDKEMW-7177 - Auto PR for rdkcentral/meta-middleware-generic-support 1382

middleware-generic.xml
Details: Reason for change: Upgrade to new release - 1.0.0 with following Bug fixes
- Implemented additional L1/L2 for libnm backends
- Addressed Coverity issues in Connectivity Monitoring Thread
- Marking official production release.
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 178bc79cac16fd803a8b4f8823dc5d10b4a1a601
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: d9e0d16c436d5494926dc6d8d8c5b394cd761c8f
=> RDKEMW-5842 - Auto PR for rdkcentral/meta-rdk-video 1508

middleware-generic.xml
Details: Reason for change: Update AAMP SRC Revision & TAG to 2.8.0
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 99c8b314cff4079f74676017c7dc2a3a9e66c3e4
=> RDKEMW-7130 - Auto PR for rdkcentral/meta-middleware-generic-support 1296

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: d62db233736a1122ac6b0301d8ac524ca096391c
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: e4dbb3d0926202954f1196f02b64fb5162f78cb9
=> RDKEMW-6718 - Auto PR for rdkcentral/meta-rdk-video 1608

middleware-generic.xml
Details: Update rfc recipe to integrate cert selector
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: d4a085c6bf7958fc54fc7dbf294209ebf89320db
=> RDK-59118 - Auto PR for rdkcentral/meta-rdk 257

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 238670bde7dfbc574e0ff4562067b989a09f090f
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 238670bde7dfbc574e0ff4562067b989a09f090f
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 631705f280c2e6dd55cde493fe4c3ad02d0c59f8
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 238670bde7dfbc574e0ff4562067b989a09f090f
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 238670bde7dfbc574e0ff4562067b989a09f090f
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 631705f280c2e6dd55cde493fe4c3ad02d0c59f8
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 238670bde7dfbc574e0ff4562067b989a09f090f
- …
=> RDKEMW-5823 - Auto PR for rdkcentral/entservices-infra 1620

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 5e798c2b9e96268cdae79abdc748f2dda3f9e8d5
=> RDK-58323 - Auto PR for rdkcentral/meta-middleware-generic-support 1588

middleware-generic.xml
Details: Added the latest changes of RFCMgr to RDKE
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: d4a085c6bf7958fc54fc7dbf294209ebf89320db
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 69fb8a2c7b2ec3a35eff4ec43a505dde718b8a2e
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 69fb8a2c7b2ec3a35eff4ec43a505dde718b8a2e
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 69fb8a2c7b2ec3a35eff4ec43a505dde718b8a2e
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 69fb8a2c7b2ec3a35eff4ec43a505dde718b8a2e
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 69fb8a2c7b2ec3a35eff4ec43a505dde718b8a2e
- Repository: …
=> RDK-59118 - Auto PR for rdkcentral/meta-rdk 1587

middleware-generic.xml
Details: Reason for change: Fix Coverity identified issues in ENTServices-Infra Repo 
Test Procedure: Regression testing on effected plugins 
Risks: Low
Signed-off-by:AkshayKumar_Gampa AkshayKumar_Gampa@comcast.com
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 924d138536d7a9d0eb42d2bc03d01cccd6fa7785
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: fc39be917ad5a50aefd3afca5dc152abc8ced781
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: fc39be917ad5a50aefd3afca5dc152abc8ced781
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 924d138536d7a9d0eb42d2bc03d01cccd6fa7785
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: fc39be917ad5a50aefd3afca5dc152abc8ced781
=> RDKEMW-6515 - Auto PR for rdkcentral/meta-middleware-generic-support 1534

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 6c2fde36a91dca3b8c3b67cf7b00b02c7c79582a
=> RDKEMW-1013 - Auto PR for rdkcentral/meta-rdk-video 1617

middleware-generic.xml
Details: …ng the build
Reason for change: Updated pkg rev with new tag.
Test Procedure: build and playback should be successful.
Risks: low
Priority: P2
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: fdf0228654b1c2b7f5bc8dba6df424b9584a2787
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 45bf53de21267781680ec568ff500444754d059e
=> RDKEMW-8249 - Auto PR for rdkcentral/meta-rdk-video 1636

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 093344d6eb1d5e0b36dc56fddf8247593a11545b
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 4fa8f44b531f0d765529f7c517b776d10172ddb8
=> RDKEMW-7169 - Auto PR for rdkcentral/meta-middleware-generic-support 1603

middleware-generic.xml
Details: Reason for change: provide read permission for migration datastore file
and provide execute permission for migration folder 
Priority: P1
Risks: Medium
Signed-off-by: Ramesh Alagarsamy <Ramesh_Alagarsamy@comcast.com>
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: b1ebbfceaf050fef4b1ab4e8f6da03cb30ae4773
=> RDKEMW-8168 - Auto PR for rdkcentral/meta-rdk-video 1649

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 07203cf09579af3b47f5578e335c34077c8d9c5f
=> RDKEMW-4216 - Auto PR for rdkcentral/meta-middleware-generic-support 1485

middleware-generic.xml
Details:  Reason for change: disabled log containing text
Test Procedure: Same as ticket
Priority: P1
Risks: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 364ff980e8fe7c87b34e93db692924eb8beb7bc4
=> RDKEMW-8319 - Auto PR for rdkcentral/meta-rdk-video 1637

middleware-generic.xml
Details:  Reason for change: disabled log containing text
Test Procedure: Same as ticket
Priority: P1
Risks: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 421975e75653ff62bdd16d172a2f279b7d647c56
=> RDKEMW-8319 - Auto PR for rdkcentral/meta-middleware-generic-support 1621

middleware-generic.xml
Details: Reason for change: Added WPEFramework restart time as 5s for to cleanly shutoff all the dependent servic
Risks: Medium
Priority: P1
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 0d057390421c7b6a726970a778f70ccbc04dc840
=> RDKEMW-8299 - Auto PR for rdkcentral/meta-rdk-video 1633

middleware-generic.xml
Details: Reason for change: Bring in latest sysint changes to develop
Test Procedure: Build RDKE image
Risks: Low
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 9b8255697acecb5fe4475b2b741590bcd3ea94f7
=> RDKEMW-8370 - Auto PR for rdkcentral/meta-middleware-generic-support 1667

middleware-generic.xml
Details: Reason for change: Update tag for Telemetry APIs migration from SystemServices to Telemetry plugin
Test Procedure: Test Telemetry - SetOptOutTelemetry and IsOptOutTelemetry APIs
Risks: Low
Priority: P2
Signed-off-by:Dineshkumar P [dinesh_kumar2@comcast.com]
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: c938c54661e3d30589ff15e94b0dc1295cdf4545
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: ce5b6bbad7744eae5ad49d147b2e34859e28d247
=> RDKEMW-7761 - Auto PR for rdkcentral/meta-rdk-video 1673

middleware-generic.xml
Details:  - backport 'Fix recompilation on rebuild without changes'
- increase size of video appsrc buffer
- request key frame every 10 seconds
Reason for change: Luna gaming app
Test Procedure: See jira ticket
Risks: None
Signed-off-by: Eugene Mutavchi <Ievgen_Mutavchi@comcast.com>
Change-Id: Idd18d6bea4dfa3a356652af19b22f419d4c4152e
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: ca89f69d653bd095875a0202add49c8ead91458c
=> RDKEMW-8618 - Auto PR for rdkcentral/meta-rdk-video 1733

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: d1ab3c2988eed0a1874cbf832aa499718af7f4d7
=> RDKEMW-6957 - Auto PR for rdkcentral/meta-middleware-generic-support 1731

middleware-generic.xml
Details: RDKEMW-4621: Xcast plugin changes
Signed-off-by: yuvaramachandran_gurusamy <yuvaramachandran_gurusamy@comcast.com>
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: a7f9bd68f02151a2a3bf962322bcb283656a2b33
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 09dea50cbb20d8a5539c1a3a36919601f4333829
=> RDKEMW-4621 - Auto PR for rdkcentral/meta-rdk-video 1745

middleware-generic.xml
Details: Deploy cla action
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: 13faf292ae89e1bec4ef17c794db534750c01c95
=> NO-TICKET - Auto PR for rdkcentral/meta-rdk 135

middleware-generic.xml
Details: Deploy cla action
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 6c591dd7e6afc2a06f46aaeae9e56b40feeab175
=> NO-TICKET - Auto PR for rdkcentral/meta-middleware-generic-support 746

middleware-generic.xml
Details: Deploy cla action
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: da8fb993d8b515577b4c7dc60959da0cad17fd6b
=> NO-TICKET - Auto PR for rdkcentral/meta-rdk-video 827

middleware-generic.xml
Details: Release PR for 1.8.8
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: f9e872ac361a3cb8324de405cebdf87cb79d76fd
=> NO-TICKET - Auto PR for rdkcentral/meta-middleware-generic-support 1762

middleware-generic.xml
Details: Release PR for 1.8.8
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 1f791ad7bc726147be8b28aef7663c1a7ce1ed17
=> NO-TICKET - Auto PR for rdkcentral/meta-rdk-video 1758

middleware-generic.xml
Details: Update the PR and PV for RFC
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 8e5771e2d3c70c1034a9032704516cab4ea257c8
=> RDKEMW-8684 - Auto PR for rdkcentral/meta-middleware-generic-support 1751

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: ae2ebbd768f631f5ac59151a32691953c89436ea
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: ae2ebbd768f631f5ac59151a32691953c89436ea
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: ae2ebbd768f631f5ac59151a32691953c89436ea
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: ae2ebbd768f631f5ac59151a32691953c89436ea
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: ae2ebbd768f631f5ac59151a32691953c89436ea
=> RDKEMW-6516 - Auto PR for rdkcentral/meta-middleware-generic-support 1763

middleware-generic.xml
Details: Deploy fossid_integration_stateless_diffscan_target_repo action
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 748166a845901fb0eb1c91441f5c6bec6df5b769
=> NO-TICKET - Auto PR for rdkcentral/meta-rdk-video 1771

middleware-generic.xml
Details: Deploy fossid_integration_stateless_diffscan_target_repo action
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: a60e3add1f4e8f5aec34db06086b1a0cf9811276
=> NO-TICKET - Auto PR for rdkcentral/meta-middleware-generic-support 1782

middleware-generic.xml
Details: Reason for change: Upgrade rbus that contains  low priority coverity fixes
Test Procedure: Tested and verified
Risks:Medium
Priority:P1
Signed-off-by: Rose Mary Benny <RoseMary_Benny@comcast.com>
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: adfb54c7871456ddf224a86163a54e494c7868f7
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: adfb54c7871456ddf224a86163a54e494c7868f7
=> RDK-58045 - Auto PR for rdkcentral/meta-rdk 1791

middleware-generic.xml
Details: Add latest sysint release 
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: aeaa17007c81ca84afe29698e1d7a2efa3ddad5e
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: c2c7e4dda27a1888e8833527786713f70637a410
=> RDKEMW-8560 - Auto PR for rdkcentral/meta-rdk-video 1741

middleware-generic.xml
Details: cloudstore and analytics removal build
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 7de637138f2e62911a6eade12c7288939cd071a1
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 5d0f5809dcdeb85bdcd7f1f56bed6670f3c04d7e
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 7de637138f2e62911a6eade12c7288939cd071a1
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 5d0f5809dcdeb85bdcd7f1f56bed6670f3c04d7e
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 7de637138f2e62911a6eade12c7288939cd071a1
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 5d0f5809dcdeb85bdcd7f1f56bed6670f3c04d7e
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: …
=> RDKEMW-8444 - Auto PR for rdkcentral/meta-middleware-generic-support 1659

middleware-generic.xml
Details: None
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: ef0bc2d927c42d3231543624c74e19959eca7c55
=> RDKEMW-7277 - Auto PR for rdkcentral/meta-middleware-generic-support 1752

middleware-generic.xml
Details: …ng the build
Reason for change: Updated pkg rev with new tag.
Test Procedure: build and playback should be successful.
Risks: low
Priority: P2
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: d2dc60a0dda15947673fd3b860d9ef8222a6b819
=> RDKEMW-8896 - Auto PR for rdkcentral/meta-middleware-generic-support 1816

middleware-generic.xml
Details: RDKEMW-7921-Update the tr69hostif release tag to 1.2.6
Reason for change: Updating the release tag
Test Procedure: Make sure the build is working fine 
Risks: Medium
Priority: P1
Signed-off-by: Vismal S Kumar <ajvismal@yahoo.com>
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: aad514a5a90a85a43b353ed8b6fcf557dae90d20
=> RDKEMW-7921 - Auto PR for rdkcentral/meta-middleware-generic-support 1851
