middleware-generic.xml
Reason for change: Remove workaround that are not used.
Risks: Low
Priority: P1
Signed-off-by: snazee925@cable.comcast.com
=> RDKEMW-2489: remove workaround fixes on Middleware

middleware-generic.xml
Reason for change: rdkshell-Remove workaround fixes on middleware Test Procedure: None
Risks: Low
Priority: P1
Signed-off-by:mkooda197@cable.comcast.com
=> RDKEMW-2925: rdkshell-Remove workaround fixes on middleware

middleware-generic.xml
Reason for change:
image assembler tv us migration support
webconfig support for tv common builds
Risks: Low
=> RDKEMW-2533: image assembler tv us migration support

middleware-generic.xml
Reason for change: Remove workaround for qtbase
Risks: Low
Priority: P1
Signed-off-by:mkooda197@cable.comcast.com
=> RDKEMW-2915: Remove workaround for qtbase

middleware-generic.xml
Details: Reason for change: Bump rdkservices-apis to 1.3.0
Risk: Medium
Priority: P1
Change-Id: Icfe2f5fe253778ac045ad5346554143722ea4796
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 20b5759a67d2c39e8c21ecb06a024398599a1bd5
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: fa9819762ff59483219d516a640c2ca69cbbda9c
=> RDK-56155 - Auto PR for rdkcentral/meta-middleware-generic-support 79

middleware-generic.xml
Details: Reason for change: Revert for change brought in webkit downstream calling play() during a seek() is allowed by the spec. And the play event should be fired even if the seek hasn't completed. Test Procedure: Check ticket
Risks: NA
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 4b9a1c1d9a3d837540a59668f28367831d0ece41
=> RDKEMW-3192 - Auto PR for rdkcentral/meta-rdk-video 87

middleware-generic.xml
Reason for change: Moved the wpeframework-networkmanager.service from meta-rdk-comcast-video to here
Test Procedure: check the command "systemctl status NetworkManager"
Risks: Medium
Priority: P1
Signed-off-by: Gururaaja ESR <gururaja_erodesriranganramlingham@comcast.com>
=> RDKEMW-3311 - NetworkManager Thunder Plugin - Systemd Service cleanup

middleware-generic.xml
Details: RDK-57093: PowerManager plugin interface change
Reason for change: Interface API arguments not to be passed by reference if
it's a primitive data type.
Test Procedure: SetPowerState & QueryPowerState sanity
Risks: LOW
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 198e9529c38afae68d867bb03f3b35649659793d
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: bf4eb6113dac7f27d1f43dea20c6f5ed378990b7
=> RDK-57093 - Auto PR for rdkcentral/meta-middleware-generic-support 179

middleware-generic.xml
Details: Reason For Change: Reverting changes made in #209 as stakeholders need to discuss and release new tag for meta-rdk-auxiliary before it can be brought in
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 91976ffc6f9774cad4bd3201b25a641d6537a005
=> RDK-56570 - Auto PR for rdkcentral/meta-middleware-generic-support 292

middleware-generic.xml
Details: Reason for change:  Updated recipes to use relative paths instead of absolute paths. 
The `MANIFEST_PATH_*` variables within the `xmidt-agent.bb` and `rdksysctl.bb` are modified to use relative paths.
Test Procedure:  Build image and verify that these components are not rebuilt when sstate mirrors are available.
Risks: Low
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: 3d5f474613d846cc4bc14bc6328e32b734a9b9c3
=> RDKOSS-228 - Auto PR for rdkcentral/meta-rdk 75

middleware-generic.xml
Details: Reason for change: Updated recipes to use relative paths instead of absolute paths.
* The `MANIFEST_PATH_*` variables within the `bootversion-loader.bb`, `uwebsockets_git.bb`,  `wlan-p2p` and `rdknativescripts.bb` are modified to use relative paths.
* `thunderstartupservices.bb` recipe was updated to modify the `0002-displaysettings-tv-deps.patch` inorder to use source dir itself instead of specifying patch dir separately.
Test Procedure: Build image and verify that these components are not rebuilt when sstate mirrors are available.
Risks: Low
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 92845f73cada36cf1ee382279f79d63570affb9d
=> RDKOSS-228 - Auto PR for rdkcentral/meta-rdk-video 258

middleware-generic.xml
Details: Reason for change : 
1) Invoke volatile-bind framework in middleware packagegroup
2) Remove dependency of vaoltile-binds recipe
Test Procedure : Successful build, Check the ticket
signed-off-by : Sindhuja <Sindhuja_Muthukrishnan@comcast.com>
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 10f541106e3434779fea4c55e5c9eab2255b2bec
=> RDK-56570 - Auto PR for rdkcentral/meta-middleware-generic-support 346

middleware-generic.xml
Details: Reason for change: wpeframework/ctrlm
should stop before secure folder to prevent
fs corruption and umount failure.
Test Procedure: Check system.log.
Risks: None
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 1e00f9b5da8af725d03116aac036e1f5607572b7
=> RDKEMW-4169 - Auto PR for rdkcentral/meta-rdk-video 348

middleware-generic.xml
Details: Reason for Change:  Removed the Script apps_prerdm.sh, since HDD_ENABLE is always false in RDKE .
- Repository: rdkcentral/meta-rdk, Merge Commit SHA: a6c0114ec78dca0e84bfc5cd0f436f15101148a0
=> RDKEMW-3586 - Auto PR for rdkcentral/meta-rdk 76

middleware-generic.xml
Details: Reason for change: OCDM service is not active after restart of the WPEFramework service 
Test Procedure: Check status of OCDM plugin and service it should in active state 
Risks: Low
Signed-off-by:AkshayKumar_Gampa AkshayKumar_Gampa@comcast.com
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 1c5d535c62ccbd692fde50c9574b5f6485f61296
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 4434937587270c907f8a390815dd55d6560898e1
=> RDKEMW-4076 - Auto PR for rdkcentral/meta-rdk-video 396

middleware-generic.xml
Details: RDKEMW-4522: Added the p2p_udhcpc script for Miracast P2P Client Mode
Reason for change: Earlier p2p_udhcpc script available in netsrvmgr which is deprecated. Hence moving it to here.
Test Procedure: Miracast should work in P2P client mode
Risks: None
Priority: P1
Signed-off-by: yuvaramachandran_gurusamy <yuvaramachandran_gurusamy@comcast.com>
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: fa2099f7b8abfbfb25c0601b7d0d497444c8abd8
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 2b90483936a530b2f82b503f2c912297219275d8
=> RDKEMW-4522 - Auto PR for rdkcentral/meta-rdk-video 498

middleware-generic.xml
Details: The common functionality in those libraries have been consolidated and so the subttxrend-app build must now depend on subttxrend-ctrl instead of the individual subtec libraries.
Test Procedure: Build and Regression Test. No new functionality.
Change-Id: I179eaa4c8475474e3eb2f99b817b18a7c9573501
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: dd871fa3618f6361f2dc6be96ecb2474e9b6acc9
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: e9c34a953a05bf3f4246d41692b5fc1fd7526dec
=> RDKEMW-4363 - Auto PR for rdkcentral/meta-rdk-video 460

middleware-generic.xml
RDK-E : libloader-app Remove AUTOINC from the PV
Risks: Low
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 9e697d60dd97d0881e1edd93c17ecf624634d1c0
=> RDKEMW-4615 - Auto PR for rdkcentral/meta-rdk-video 514

middleware-generic.xml
Details:     Reason for change: LibUV was not linked to uwebsocket
Test Procedure: build should be successful.
Risks: low
Priority: P2
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 1657e898d57975027d6bc5f984196eceac71ec03
=> RDKEMW-3466 - Auto PR for rdkcentral/meta-rdk-video 564

middleware-generic.xml
Details: Reason for change: missing WAI support in RDK-E
Test Procedure: described in the ticket
Implements: code changes in AuthService and DeviceProvisioning
Risks: No
Source: COMCAST
License: Apache-2.0
Upstream-Status: Pending
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 08f3e800d107b732e36530b62b2ea6cabe090585
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 3d004077dbd51e468f84c8bf37099b62e5bb185a
=> RDKEMW-3788 - Auto PR for rdkcentral/meta-rdk-video 669

middleware-generic.xml
Details: Reason for change: Removing the qtvirtualkeyboard support. Test Procedure:Build size should reduce. Spotify app search should work. Risks: low
Priority: P2
Change-Id: I10d9952818cd4a8c487050f15a3cde8b08da80d9
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: c8d591327984b9129bfa07051f1a5a662587bd6b
=> RDKEMW-5274 - Auto PR for rdkcentral/meta-middleware-generic-support 693

middleware-generic.xml
Details: Reason for change: Abstracted Playready API to gstreamer utils
Risks: None
Priority: P1
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: ef89eb960abadcb0f11b005857c0a48567e54bbb
=> RDKEMW-4807 - Auto PR for rdkcentral/meta-middleware-generic-support 859

middleware-generic.xml
Details: Reason for change: Fix crash in ~BitmapTextureGL() Test Procedure:
1) Web apps smoke testing
2) Monitor Stack trace portal for new instances
Priority: P1
Risks: Low
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 2685a7f6bcd86f833d61e85a89801012a7854fb9
=> RDKEMW-2744 - Auto PR for rdkcentral/meta-rdk-video 1138

middleware-generic.xml
Details: Tubi app crashes in CachedResourceStreamingClient::responseReceived SEGV
There is an existing fix upstream in WPEWebKit wpe-2.46 and wpe-2.38.
https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1531
Bring it in as a patch.
https://bugs.webkit.org/show_bug.cgi?id=266973
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 260b12a7edb0c54c3566a73359a4d6fa1dbabd92
=> SERXIONE-7573 - Auto PR for rdkcentral/meta-rdk-video 974

middleware-generic.xml
Details: Reason for change: Added the securemount.service & requires RequiresMountsFor =/opt/secure and removed from wpeframework.service
Risks: Medium
Priority: P1
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: e4577d48fd075255ff616ceeefe311ab68efb65b
- Repository: rdkcentral/thunder-startup-services, Merge Commit SHA: e5082ec7c42117b5ebef3f76b77a0d0eeb6f1502
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: d83f3d4f03c6a182b3538db464f9130888766445
=> RDKEMW-5954 - Auto PR for rdkcentral/meta-rdk-video 1226

middleware-generic.xml
Reason for change: Update SHA for MW layer to reflect tr69hostif component release
Test Procedure: Build RDKE image
Risks: Low
=> RDK-58539: Canary firmware upgrade support

middleware-generic.xml
Details: Reason for change: Currently KillSignal and ExecStop for WPEFramework Service is defined as SIGKILL and kill -9. This must be changed to use SIGTERM to avoid improper shutting down of the thunder services.
Risks: Medium Priority: P1
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 3f75619956ffc422a1a70720b34e9511800cb8dc
=> RDKEMW-6540 - Auto PR for rdkcentral/meta-rdk-video 1261

middleware-generic.xml
WPEFramework crashwith signature WPEFramework::Plugin::USBDeviceImplementation::libUSBEventsHandlingThread with fingerprint 14820164 during Reboot testing. [RDKMW][RTK-XIONE] WPEFramework crash Observed while Launching and Playing XUMO Play.
Test Procedure:
Reboot testing needs to do. No. of Reboots: Atleast 50 Reboots. Refer RDKEMW-6934, RDKEMW-6935, RDKEMW-6785
Risks: High
Priority: P1
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 8690ed0a6a15a467b2db26ca5e4c3945762ee9fe
- Repository: rdkcentral/meta-middleware-generic-support, Merge Commit SHA: 0f7973400ae43a5bb0c3ed0dfb78192568075894
=> RDKEMW-6934 - Auto PR for rdkcentral/meta-middleware-generic-support 1302

middleware-generic.xml
Details: getDolbyVisionMode api fails to return "Dark/Bright" in response for AVOutput plugins.
Reason for change: Added condition in getDolbyVisionMode() to return error for non DV content.
Test Procedure: as per JIRA
Risks: None
Priority: P2
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 7713c3410dcbb145c7655c9cf2edd3b20ac8cf4b
=> RDKEMW-6681 - Auto PR for rdkcentral/meta-rdk-video 1303

middleware-generic.xml
Details: Reason for change: Upgrade to new release - 0.25.0 with following Bug fixes
- Implemented SetHostname method which can send device's hostname over DHCP explicitly
- Implemented L1/L2 for netsrvmgr (RDK), libnm backends
- Clamped the WIFI Noise value to be within 0 dBm to -96 dBm
- Handled Plugin Termination sequence to stop the monitoring thread before exit
- Handled out-of-process plugin configuration as string
- Fixed Router Discovery to handle dual interface
- Fixed Internet Connectivity Monitoring to not to poll unless requested
- Addressed coverity reported issue
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: a62a55f72e2499d9873cb85a2c6eff9262c01c82
=> RDKEMW-6225 - Auto PR for rdkcentral/meta-rdk-video 1496

middleware-generic.xml
Details: Reason for change: OCDM and TextToSpeech Plugins Not Restarting After Crash 
Test Procedure: Check weather after crash OCDM TextToSpeech plugins should restart 
Risks: Low
Signed-off-by:AkshayKumar_Gampa AkshayKumar_Gampa@comcast.com
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: dc03e0b7971e7009b7c1c183cbcc433783409924
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: dc03e0b7971e7009b7c1c183cbcc433783409924
=> RDKEMW-7538 - Auto PR for rdkcentral/meta-middleware-generic-support 1530

middleware-generic.xml
Details: Reason for change: Debug logging required for wpa_supplicant
Test Procedure: Ensure debug logging enabled for supplicant
Risks: medium
Signed-off-by: jincysaramma_sam@comcast.com
- Repository: rdkcentral/meta-rdk-video, Merge Commit SHA: 4ecc527f8323f56771d60a2e0603c447f02377da
=> RDKEMW-8405 - Auto PR for rdkcentral/meta-rdk-video 1670

middleware-generic.xml
Details: Reason for Change:Validated the Thunder R4.4.3 + RDK patch using the BigJSONTest Test Plugin. The TestConsumer receives only the first three events. The fourth event is not notified to the consumer—it gets stuck at the Thunder layer. The fifth event is received by the Thunder layer but gets mixed up with the pending fourth message, causing deserialization errors due to the combined data from both messages. After this point, no further events are received or notified, and the Thunder layer enters a bad state. I suspected the Metro changes introduced in PR #1625. After reverting those changes and revalidating, the issue was resolved
Test Procedure:Please refer to the ticket description. 
Risks: Medium
Priority: P1
- Repository: …
=> RDKEMW-8985 - Auto PR for rdkcentral/meta-rdk-video 1797
